---
- name: Validar parámetros obligatorios
  ansible.builtin.assert:
    that:
      - repo_url is defined
      - namespace_name is defined
      - >
        (
          (gitops_rbac_group_bindings is defined)
          and
          (gitops_rbac_group_bindings | length > 0)
        )
        or
        (
          (admin_group is defined)
          and
          (reader_group is defined)
        )
    fail_msg: "Faltan parámetros obligatorios: repo_url, namespace_name y RBAC de grupos (gitops_rbac_group_bindings o admin_group/reader_group)"

- name: Validar nombre del namespace
  ansible.builtin.assert:
    that:
      - namespace_name is match('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')
    fail_msg: "El namespace no cumple el formato permitido por Kubernetes"
